GET http://localhost:1337/api/productos/ElectroMundo
Accept: application/json
Content-Type: application/json


{
        "data": {
            "nombre": "EcoDeportes",
            "direccion": "Av. Verde 99, Ciudad Natural",
            "telefono": "9988776655",
            "correo": "contacto@ecodeportes.com",
            "nombreContacto": "Fernando Salazar",
            "productos": ["jp03576soriitwpywbx09yt2", "k8o0fmqwyz6h6rukj01g0y3q"]
        }
}